project:
  type: website
  output-dir: docs  # This is required for GitHub Pages, ensures that GitHub Pages can find the published website files.

website:
  title: "EMME Version Comparison"
  sidebar:
      style: "docked"
      search: true
      contents:
          - section: "EMME OpenPath VS. EMME 4.3.7"
            contents:
            - section: "Highway Network"
              contents:
              - notebooks/VMT_VHT_VHD.ipynb
              - notebooks/Speed.ipynb
            - section: "Traffic Skims"
              contents:
              - notebooks/TrafficSkimAM.ipynb
              - notebooks/TrafficSkimPM.ipynb
            - section: "Transit Skims"
              contents:
              - notebooks/TransitSkimAM_compare.ipynb
              - notebooks/TransitSkimPM_compare.ipynb
            - section: "Tests"
              contents:
              - notebooks/TransitSkimAM_OpenPaths_OBS.ipynb
              - notebooks/TransitSkimAM_EMME437_OBS.ipynb
              - notebooks/TransitSkimAM_EMME437_transitAssign.ipynb
              - notebooks/TransitSkimAM_compare_test1.ipynb
              - notebooks/TransitSkimAM_compare_test2.ipynb
              - notebooks/TransitSkimAM_compare_test3.ipynb
            

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



