project:
  type: website
  output-dir: docs  # This is required for GitHub Pages, ensures that GitHub Pages can find the published website files.
  render:
    - "notebooks/*"

website:
  title: "EMME Version Comparison"
  navbar:
    left:
      - href: notebooks/VMT_VHT_VHD.ipynb
        text: Home
  sidebar:
      style: "docked"
      search: true
      contents:
          - href: notebooks/VMT_VHT_VHD.ipynb
            text: "Home"
          - section: "EMME OpenPath VS. EMME 4.3.7"
            contents:
            - section: "Highway Network"
              contents:
              - notebooks/VMT_VHT_VHD.ipynb
            - section: "Traffic Skims"
              contents:
              - notebooks/TrafficSkimAM.ipynb
              - notebooks/TrafficSkimPM.ipynb
            - section: "Transit Skims"
              contents:
              - notebooks/TransitSkimAM_compare.ipynb
              - notebooks/TransitSkimPM_compare.ipynb
            

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



